# Default values for mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.hub.docker.com/library/mariadb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: NodePort
  port: 3306

  # persistence:
  #   ## @param primary.persistence.enabled Enable persistence on MariaDB primary replicas using a `PersistentVolumeClaim`. If false, use emptyDir
  #   ##
  #   enabled: true
  #   storageClass: "asterion-dev-sc-localfs1"
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 10Gi
