config:
  aws:defaultTags:
    tags:
      environment: prod
  aws:region: ap-southeast-2
  org-asterion:accountId: 016114654101
  org-asterion:environment: prod
  org-asterion:environments: 
    - dev
    - test
    - prod
  org-asterion:iamGroupName: asterion-admins
  org-asterion:iamUsersToAdd: 
    users:
    - shawn
    - james
    - dj
    - kyle
  org-asterion:masterAccountId: 814941672613
  org-asterion:orgId: o-s4sfk2iwpm
  org-asterion:rootId: r-9kqq