config:
  aws:defaultTags:
    tags:
      environment: test
  aws:region: ap-southeast-2
  org-asterion:accountId: 022525405108
  org-asterion:masterAccountId: 814941672613
  org-asterion:parentId: ou-9kqq-u2jjfher
  org-asterion:currentOrgName: shawng
  org-asterion:environment: test
  org-asterion:environments: 
    - dev
    - test
    - prod
  org-asterion:iamUsersToAdd: 
    users:
    - shawn
    - james
    - dj
    - kyle