config:
  aws:defaultTags:
    tags:
      environment: dev
  aws:region: ap-southeast-2
  org-asterion:currentOrgName: shawng
  org-asterion:environment: dev
  org-asterion:iamUsersToAdd: 
    users:
    - shawn
    - james
    - dj
    - kyle