apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  labels: {{- include "mariadb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi